name: Django tests

on:
  push:
    branches:
      - main

jobs:
  HotelTesting:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: hotel
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: qwerty
        ports:
          - 5432:5432
    steps:
      - name: Cache ğŸ’¾
        uses: actions/checkout@v4
      - name: Setup python ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies âš™ï¸
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./backend
      - name: Coverage report ğŸ“Š
        run: |
          pip install coverage
          coverage run manage.py test applications.hotel.tests
          coverage report 
        working-directory: ./backend
        env:
          DATABASE_NAME: hotel
          DATABASE_USER: postgres
          DATABASE_PASS: qwerty
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
      - name: Django testing ğŸ§ª
        run: |
          python3 manage.py test applications.hotel.tests
        working-directory: ./backend

  HabitacionTesting:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: hotel
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: qwerty
        ports:
          - 5432:5432
    steps:
      - name: Cache ğŸ’¾
        uses: actions/checkout@v4
      - name: Setup python ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies âš™ï¸
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./backend
      - name: Coverage report ğŸ“Š
        run: |
          pip install coverage
          coverage run manage.py test applications.habitacion.tests
          coverage report 
        working-directory: ./backend
        env:
          DATABASE_NAME: hotel
          DATABASE_USER: postgres
          DATABASE_PASS: qwerty
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
      - name: Django testing ğŸ§ª
        run: |
          python3 manage.py test applications.habitacion.tests
        working-directory: ./backend